apiVersion: batch/v1
kind: Job         # We are testing the Job resource type
metadata:
  name: consumer  # A name must be given to the Job type in the metadata section
spec:                     # This is the specification where we can even put the number of replicas
  template:               # Specified info needed to run the pod and what runs in the pod
    metadata:
      labels:
        app: consumer        # some label to give to this pod (see the matching label above)
    spec:                 # actual specification
      containers:
      - name: consumer       # this is going to be used for DNS name
        # Change the IP address to where you are running this
        image: 129.114.25.172:5000/couchdb  # this is the image in registry accessible
        imagePullPolicy: Always  # This forces the node to pull the image

                                                                                                       # iterations so that we have time to do an exec
                                                                                                       # and open a shell to the running pod
      restartPolicy: Never  # we ask Kubernetes not to restart
